### ISSUE TITLE
TypeError (0 , $csb___mui_system.private_safeDarken) is not a function

### ISSUE THREAD

**Issue by mrdulin** [Learus/react-material-ui-carousel#220]
Try getting started with it, but got the below error:

```zsh
TypeError: (0 , $csb___mui_system.private_safeDarken) is not a function
    at eval (https://6jnq94.csb.app/node_modules/@mui/material/styles/experimental_extendTheme.js:106:86)

    at Array.forEach (<anonymous>)

    at extendTheme (https://6jnq94.csb.app/node_modules/@mui/material/styles/experimental_extendTheme.js:89:35)

    at $csb$eval (https://6jnq94.csb.app/node_modules/@mui/material/styles/CssVarsProvider.js:36:59)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/@mui/material/styles/index.js:242:30)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/@mui/material/index.js:17:21)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/react-material-ui-carousel/dist/components/Styled.js:19:18)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/react-material-ui-carousel/dist/components/CarouselItem.js:36:16)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/react-material-ui-carousel/dist/components/Carousel.js:34:22)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/node_modules/react-material-ui-carousel/dist/index.js:6:34)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/src/App.js:10:55)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at c (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112290)

    at $csb$eval (https://6jnq94.csb.app/src/index.js:6:35)

    at H (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:99956)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:112675)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:123056)

    at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:122555)

    at https://codesandbox.io/static/js/sandbox.df283ba5e.js:1:322479

    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4328)
​
```

[codesandbox](https://codesandbox.io/s/react-material-ui-carousel-issue-6jnq94?file=/src/App.js)

**Comment by vasiline2256** [comment]
getting the same error for: `@mui/material/styles` in `codesandbox` what is the cause?
